### ISSUE TITLE
CFG ❤️‍🔥 CSG

### ISSUE THREAD

**Issue by THinnerichs** [Herb-AI/HerbGrammar.jl#42] opened 2024-01-16 15:27 UTC
Combine CFG and CSG and get rid of the redundant enumerators. However, keep the `@cfgrammar` macro. Make sure the code works afterwards.

**Comment by ReubenJ** [comment] 2024-01-16 15:37
Duplicate of #31, btw. I think the note about renaming the combined version to "Grammar" still holds, right?

**Closed** 2024-02-01 16:08 UTC
